Lubycon/clelab-backend

- .github/workflows/slack.yml
> chore: PR slack notification 버전 변경

- src/main/java/com/lubycon/curriculum/base/error/ErrorCode.java
- src/main/java/com/lubycon/curriculum/base/error/ErrorResponse.java
- src/main/java/com/lubycon/curriculum/base/error/GlobalExceptionHandler.java
- src/main/java/com/lubycon/curriculum/base/error/exception/BusinessException.java
- src/main/java/com/lubycon/curriculum/base/error/exception/EntityNotFoundException.java
- src/main/java/com/lubycon/curriculum/base/error/exception/InvalidValueException.java
예외 처리에 공통으로 사용할 응답 객체와 커스텀 예외에 사용할 최상위 예외, 전역으로 발생하는 예외를 처리할 예외처리 컨트롤러를 추가했습니다.
resolved #13 
요건 바로 머지되면 좋을 것 같아서 최대한 빨리 리뷰봐주심 좋을 것 같아효!! 👀
> feat: 공통 예외 응답 객체 및 예외처리 컨트롤러 추가

- src/main/java/com/lubycon/curriculum/base/error/GlobalExceptionHandler.java
- src/main/java/com/lubycon/curriculum/section/api/SectionApi.java
- src/main/java/com/lubycon/curriculum/section/dto/NextSectionResponse.java
- src/main/java/com/lubycon/curriculum/section/dto/PrevSectionResponse.java
- src/main/java/com/lubycon/curriculum/section/dto/SectionResponse.java
- src/main/java/com/lubycon/curriculum/section/repository/SectionRepository.java
- src/main/java/com/lubycon/curriculum/section/service/SectionService.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
- src/test/java/com/lubycon/curriculum/section/repository/SectionRepositoryTest.java
- src/test/java/com/lubycon/curriculum/section/service/SectionServiceTest.java
- src/test/resources/make-curriculum.sql
- 통일성을 위해 null값이 아닌 빈 객체를 반환하게 변경
- 섹션 내용을 가져오는 값을 order에서 section_id으로 변경 [(논의한 슬랙 링크)](https://lubycon-hub.slack.com/archives/C01U74A4BHV/p1619772417027800)
- GlobalExceptionHandler에서 @Slf4j 삭제 (로깅하는 곳이 없음)
resolved #19
> refactor: API 리뷰 내용을 바탕으로 API 수정

- build.gradle
Querydsl 사용을 위해 관련 설정을 추가했습니다.
gradle 설정 이외에는 변경한 부분이 없어 문제가 없다면 빠르게 어프룹해주시면 감사할 것 같아요!! 🙏
resolved #24
> chore: Querydsl 관련 설정 추가

- .github/workflows/slack.yml
[슬랙봇 v1.2.0 릴리즈 🚀  기념](https://lubycon-hub.slack.com/archives/C017Y3KRWJ1/p1620136991068300) 버전 변경! 🎉
단순 버전 변경만 했기 때문에 바로 Approve해주셔도 될 것 같습니다! (main에 바로 푸시가 안되네여 ... ㅎㅎㅠㅠ)
resolved #29
> chore: Lubycon Github Reviewer Slack Notify Action 버전 변경

- .gitignore
- build.gradle
- src/main/resources/application-prod.yml
- src/test/resources/application-test.yml
데이터 베이스를 인메모리 데이터 베이스에서 관계형 데이터 베이스로 변경하기 위해 AWS RDS를 설정합니다.
AWS 설정 변경사항이라, 바로 merge하겠습니다!
resolved #31
> chore: AWS RDS 설정 추가

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
프론트 서버에서 요청을 보낼 수 있게 하기 위해 CORS 설정을 추가했습니다.
단순 설정 추가만 한 PR이여서 바로 머지하도록 하겠습니다! 🙇‍♀️🙌
resolved #27
> chore: CORS 설정 추가

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
[PR에 달렸던 코멘트](https://github.com/Lubycon/clelab-backend/pull/33) 처리한 부분입니다!
resolved #34
> chore: CORS origin 범위 축소

- build.gradle
- lombok.config
일정 코드 커버리지를 넘기지 못하면 빌드가 안되는 무시무시한 라이브러리가 있다고 해서 적용해봤습니다 ... 😈 ([참고자료](https://woowabros.github.io/experience/2020/02/02/jacoco-config-on-gradle-project.html))
저는 JaCoCo 적용해보는게 처음인데 혹시 다른 분들 중에서 JaCoCo 사용해보신분 계신가요? 어땠는지 경험 공유해주시면 감사할 것 같아여!! 🙌🙏
resolved #36
> chore: JaCoCo 설정

- .github/workflows/qa-deploy.yml
> chore: QA Github Action 추가

- src/main/resources/application-qa.yml
> chore: qa 설정파일 추가

- .github/workflows/qa-deploy.yml
- src/main/resources/application-qa.yml
QA와 LIVE 서버를 분리하기 위해, QA용 Github Action 설정을 추가하고, QA용 설정 파일을 추가했습니다.
resolved #40
> chore: QA/LIVE 서버 분리

- .github/workflows/deploy.yml
- .github/workflows/slack.yml
단순히 설정파일에서 환경 이름만 변경했기 때문에 바로 merge하겠습니다!
> chore: live github action 환경 이름 변경

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
[CORS 도메인 추가 요청](https://lubycon-hub.slack.com/archives/C01U74A4BHV/p1621680383011700)이 들어와서 CORS *.clelab.io 도메인 추가
단순 도메인 추가건이라 바로 머지하도록 하겠습니다!
> chore: CORS 도메인 추가

- src/main/java/com/lubycon/curriculum/curriculum/dto/IntroResponse.java
- src/main/java/com/lubycon/curriculum/curriculum/dto/v2/CurriculumSectionsResponseV2.java
- src/main/java/com/lubycon/curriculum/curriculum/dto/v2/IntroResponseV2.java
- src/main/java/com/lubycon/curriculum/curriculum/service/CurriculumService.java
- src/main/java/com/lubycon/curriculum/section/api/v2/SectionV2Api.java
- src/main/java/com/lubycon/curriculum/section/model/IntroDescription.java
- src/test/java/com/lubycon/curriculum/curriculum/service/CurriculumServiceTest.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
> refactor: v1/v2 버전 분리

- src/main/java/com/lubycon/curriculum/curriculum/api/CurriculumApi.java
- src/main/java/com/lubycon/curriculum/section/api/v2/SectionV2Api.java
v2 다른 api url(curriculums/{curriculumId}/sections/{sectionId}, curriculums)에도 추가
> refactor: v2 다른 api url에도 추가

- src/main/java/com/lubycon/curriculum/CurriculumApplication.java
- src/main/java/com/lubycon/curriculum/base/error/ErrorCode.java
- src/main/java/com/lubycon/curriculum/subscribe/api/SubScribeApi.java
- src/main/java/com/lubycon/curriculum/subscribe/domain/Email.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/EmailDto.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/TypeformAnswer.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/TypeformResponse.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/TypeformSubscribeRequest.java
- src/main/java/com/lubycon/curriculum/subscribe/exception/TypeFormSecretNotEquals.java
- src/main/java/com/lubycon/curriculum/subscribe/filter/TypeformFilter.java
- src/main/java/com/lubycon/curriculum/subscribe/repository/EmailRepository.java
- src/main/java/com/lubycon/curriculum/subscribe/service/SubscribeService.java
- src/main/resources/application.yml
- src/test/java/com/lubycon/curriculum/subscribe/api/SubScribeApiTest.java
- src/test/java/com/lubycon/curriculum/subscribe/service/SubscribeServiceTest.java
> Feat: Typeform 이메일 API와 연동 (develop)

- src/test/java/com/lubycon/curriculum/base/ApiTest.java
- src/test/java/com/lubycon/curriculum/subscribe/api/SubScribeApiTest.java
- src/test/resources/application-test.yml
> test: Typeform 인증키 필터 테스트 추가

- src/main/java/com/lubycon/curriculum/subscribe/filter/TypeformFilter.java
> feat: TypeformFilter 생성자 추가

- build.gradle
- src/main/resources/logback-spring.xml
> chore: 에러 모니터링 도구(Sentry) 사용 설정 추가 (develop)

- build.gradle
- src/main/resources/logback-spring.xml
에러 모니터링 도구로 팀내에서 채택한 Sentry 설정을 추가했습니다.
resolved #65
> chore: 에러 모니터링 도구 추가

- .ebextensions/00-makeFiles.config
Elastic Beanstalk에 로그 관련 설정을 추가했습니다. 
https://www.slideshare.net/awskorea/aws-86614815
위 구조를 참고해서 구현할 예정입니다! 👀
resolved #70
> chore: ebextensions에 로그 관련 설정 추가

- src/main/java/com/lubycon/curriculum/subscribe/dto/EmailSenderDto.java
- src/main/java/com/lubycon/curriculum/subscribe/service/SendEmailService.java
이메일 이름을 넣어 개인화 하는 양식으로 변경하게 수정했습니다.
바로 라이브에 반영되어야 하는거라 선머지하겠읍니당 ㅎㅎ
resolved #79
> refacoring: 이메일 개인화 양식으로 변경

- build.gradle
- src/main/java/com/lubycon/curriculum/CurriculumApplication.java
- src/main/java/com/lubycon/curriculum/base/config/LogConfig.java
요청/응답 로그 확인에 불편함이 있어서 AOP를 사용해서 모든 요청과 응답에 로그를 추가하게 변경했습니다.
resolved #73
> chore: 모든 요청/응답에 로그 추가

- build.gradle
- src/main/resources/application-prod.yml
- src/main/resources/application-qa.yml
- src/main/resources/logback-spring.xml
로그 형식을 JSON으로 수정했습니다!
AS-IS
TO-BE
resolved #81
> chore: 로그 포맷 JSON으로 변경

- src/main/java/com/lubycon/curriculum/curriculum/dto/v2/IntroResponseV2.java
인트로의 구성이 없는 경우 보여주지 않게 하도록해서 Nullable하게 변경했습니다.
resolved #87 
기본적인 null check 로직들이라 바로 머지할게요!
> fix: 인트로 매핑 객체들 Nullable하게 처리

- src/main/java/com/lubycon/curriculum/base/annotation/NoLogging.java
- src/main/java/com/lubycon/curriculum/base/api/BaseController.java
- src/main/java/com/lubycon/curriculum/base/config/LogConfig.java
health check하는 부분 로깅 때문에 너무 노이즈해서 health check는 로깅을 하지 않게 표시했습니다.
간단한 설정이라 바로 머지하겠습니다!
resolved #89
> chore: 로그 제외 커스텀 어노테이션 만들기

- src/main/java/com/lubycon/curriculum/base/error/ErrorCode.java
- src/main/java/com/lubycon/curriculum/base/error/GlobalExceptionHandler.java
- src/main/java/com/lubycon/curriculum/subscribe/api/SubScribeApi.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/SubscribeRequest.java
- src/main/java/com/lubycon/curriculum/subscribe/dto/SubscribeResponse.java
- src/main/java/com/lubycon/curriculum/subscribe/exception/ConflictEmailException.java
- src/main/java/com/lubycon/curriculum/subscribe/repository/EmailRepository.java
- src/main/java/com/lubycon/curriculum/subscribe/service/SubscribeService.java
- src/main/java/com/lubycon/curriculum/subscribe/validation/SubscribeValidator.java
- src/test/java/com/lubycon/curriculum/subscribe/api/SubScribeApiTest.java
- src/test/resources/make-email.sql
구독 신청 기능을 추가하기로 해서, 구독 관련 api를 추가했습니다.
resolved #86
> feat: 구독 신청 api 추가

- src/main/java/com/lubycon/curriculum/curriculum/repository/CurriculumRepository.java
- src/main/java/com/lubycon/curriculum/curriculum/service/CurriculumService.java
리스트 전체보기 api를 호출 할 때, 최신순 먼저 나오게 변경
resolved #94
> fix: 리스트 최신순으로 정렬되게 변경

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
QA 도메인(https://qa.clelab.io)을 CORS origin에 추가한다.
resolved #99
> fix: QA 도메인 CORS 오리진에 추가

- src/main/java/com/lubycon/curriculum/subscribe/dto/EmailSenderDto.java
> fix: 이메일 받는 사람 리스트 숨은참조 -> 수신인으로 변경

- src/main/java/com/lubycon/curriculum/section/dto/SectionResponse.java
미리보기를 위해 섹션 API에 썸네일을 추가한다.
resolved #111
> fix: 섹션 API에 썸네일 필드 추가

- src/main/java/com/lubycon/curriculum/curriculum/domain/Curriculum.java
- src/main/java/com/lubycon/curriculum/curriculum/repository/CurriculumCustomRepository.java
- src/main/java/com/lubycon/curriculum/curriculum/repository/CurriculumCustomRepositoryImpl.java
- src/main/java/com/lubycon/curriculum/curriculum/repository/CurriculumRepository.java
- src/main/java/com/lubycon/curriculum/curriculum/service/CurriculumService.java
- src/test/java/com/lubycon/curriculum/curriculum/repository/CurriculumRepositoryTest.java
- src/test/java/com/lubycon/curriculum/curriculum/service/CurriculumServiceTest.java
- src/test/resources/make-curriculum.sql
- src/test/resources/make-four-curriculums-only.sql
코스 표시 여부 컬럼을 추가하고, 표시 여부에 따라 코스 리스트를 보여주게 변경했습니다.
resolved #118
> feat: 코스 표시 여부 컬럼 추가 

- src/main/java/com/lubycon/curriculum/curriculum/domain/Curriculum.java
- src/main/java/com/lubycon/curriculum/curriculum/dto/CurriculumResponse.java
- src/main/java/com/lubycon/curriculum/curriculum/dto/SaveCurriculums.java
- src/main/java/com/lubycon/curriculum/curriculum/dto/SectionTitlesResponse.java
- src/main/java/com/lubycon/curriculum/curriculum/repository/CurriculumRepository.java
- src/main/java/com/lubycon/curriculum/curriculum/service/CurriculumService.java
- src/main/java/com/lubycon/curriculum/section/api/v2/SectionV2Api.java
- src/main/java/com/lubycon/curriculum/section/domain/Section.java
- src/main/java/com/lubycon/curriculum/section/dto/NextSectionResponse.java
- src/main/java/com/lubycon/curriculum/section/dto/PrevSectionResponse.java
- src/main/java/com/lubycon/curriculum/section/repository/SectionCustomRepository.java
- src/main/java/com/lubycon/curriculum/section/repository/SectionCustomRepositoryImpl.java
- src/main/java/com/lubycon/curriculum/section/repository/SectionRepository.java
- src/main/java/com/lubycon/curriculum/section/service/SectionService.java
- src/test/java/com/lubycon/curriculum/curriculum/service/CurriculumServiceTest.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
- src/test/java/com/lubycon/curriculum/section/repository/SectionRepositoryTest.java
- src/test/java/com/lubycon/curriculum/section/service/SectionServiceTest.java
- src/test/resources/make-curriculum.sql
- src/test/resources/make-four-curriculums-only.sql
기존에 id값을 통해 코스, 섹션 정보를 가져온 api를 SEO 점수를 높이기 위해 url slug를 통해 가져오도록 변경했습니다.
resolved #119
> feat: URL 인식 가능한 단어로 바꾸게 변경

- src/main/java/com/lubycon/curriculum/blog/domain/Blog.java
- src/main/java/com/lubycon/curriculum/section/dto/BlogResponse.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
- src/test/resources/make-curriculum.sql
사용자들은 클랩이 추천한 아티클을 보고 아티클을 더 쉽게 선택할 수 있다.
resolved #131
> feat: 클랩픽 컬럼 추가

- src/main/java/com/lubycon/curriculum/email/service/SubscribeAuthEmailService.java
- src/main/resources/application.yml
- src/test/java/com/lubycon/curriculum/email/service/SubscribeAuthEmailServiceTest.java
- src/test/resources/application-test.yml
> test: 이메인 인증 템플릿 테스트 코드 추가

- src/main/java/com/lubycon/curriculum/blog/domain/Blog.java
- src/main/java/com/lubycon/curriculum/section/domain/Section.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
- src/test/resources/make-curriculum.sql
블로그 링크들도 정렬 순서에 따라 가져오게 처리한다.
resolved #129
> 블로그 링크 order_by 추가

- src/main/java/com/lubycon/curriculum/blog/domain/Blog.java
- src/main/java/com/lubycon/curriculum/section/dto/BlogResponse.java
- src/test/java/com/lubycon/curriculum/section/api/SectionApiTest.java
- src/test/resources/make-curriculum.sql
블로그에 작성자 컬럼을 추가한다.
resolved #138
> feat: 블로그에 작성자 컬럼 추가 

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
> fix: cors all open

- src/main/java/com/lubycon/curriculum/blog/api/BlogApi.java
- src/main/java/com/lubycon/curriculum/blog/domain/Blog.java
- src/main/java/com/lubycon/curriculum/blog/exception/BlogNotFoundException.java
- src/main/java/com/lubycon/curriculum/blog/service/BlogService.java
- src/main/java/com/lubycon/curriculum/section/dto/BlogResponse.java
- src/test/java/com/lubycon/curriculum/blog/api/BlogApiTest.java
- src/test/java/com/lubycon/curriculum/blog/service/BlogServiceTest.java
- src/test/resources/make-curriculum.sql
사용자는 클랩 글을 읽고 박수를 눌러 만족도를 표현할 수 있다
resolved #144
> feat: 박수 API 추가

- src/main/java/com/lubycon/curriculum/base/config/WebConfig.java
> fix: CORS 모든 Http Method 허용하게 변경

- build.gradle
log4j의 취약점을 해결하기 위해 버전 업데이트를 한다.
ref. https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot
> log4j 버전 업데이트 

- .github/workflows/prod-deploy.yml
- deploy.sh
> chore: Elastic Beanstalk 삭제
